version: "3.3" # версия формата файла Docker-Compose

services:    
  backend:    
    image: gitlab.praktikum-services.ru:5050/std-019-002/sausage-store/sausage-backend:latest
    container_name: backend
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DATABASE}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
    networks:
      - sausage-store
  backend-report:
    build:
      context: ./backend-report 
      dockerfile: ./backend-report/Dockerfile 
    image: gitlab.praktikum-services.ru:5050/std-019-002/sausage-store/backend-report:latest
    container_name: backend-report
    environment:
      DB: ${REPORTS_MONGODB_URI}
    networks:
      - sausage-store
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-019-002/sausage-store/frontend:${FRONTEND_VERSION}
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - sausage-store
    restart: always

networks:
  sausage-store:
