stages:
	- build
	- release
	
variables:
   VERSION: 1.0.${CI_PIPELINE_ID}
   MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
   JAVA_OPTS: -XX:MaxRAMPercentage=90 # для того, чтобы Maven не съел всю свободную оперативку
	
build-backend-code-job:
  stage: build
  rules:
    changes:
      - backend/**/*
  script:
    - echo "BACKEND_JOB=$CI_JOB_ID" >> backend.env
    - cd backend
    - mvn package -Dmaven.repo.local=${CI_PROJECT_DIR}/backend/.m2/repository -Dversion.application=${VERSION}
    - cd target
    - mkdir java
    - mv sausage-store-${VERSION}.jar java
  artifacts:
    paths:
      - backend/target/java/sausage-store-${VERSION}.jar
      - ${CI_PROJECT_DIR}/.m2/repository
      - ${CI_PROJECT_DIR}/backend/settings.xml
    reports:
      dotenv: backend.env
  cache:
    key: backend_cache
    paths:
      - ${CI_PROJECT_DIR}/.m2/repository # для хранения зависимости бекенда

upload-backend-release-job:
  stage: release
  rules:
    changes:
      - backend/**/*
  needs:
    - build-backend-code-job
  script:
    - cd backend
    - mvn -Dmaven.repo.local=${CI_PROJECT_DIR}/backend/.m2/repository -s ${CI_PROJECT_DIR}/backend/settings.xml -Dversion.application=${VERSION} -DskipTests deploy
  cache:
    key: backend_cache
    paths:
      - ${CI_PROJECT_DIR}/.m2/repository # для хранения зависимости бекенда
