stages:
  - build
  - release
  - notify
variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/backend/.m2/repository
  JAVA_OPTS: -XX:MaxRAMPercentage=90 # для того, чтобы Maven не съел всю свободную оперативку

build-backend-code-job:
  stage: build
  script:
    - echo "BACKEND_JOB=$CI_JOB_ID" >> backend.env
    - cd backend
    - echo "VERSION=${VERSION}" >> version.txt
    - pwd && ls -la
    - cat version.txt
    - mvn package -Dmaven.repo.local=${CI_PROJECT_DIR}/backend/.m2/repository -Dversion.application=${VERSION}
    - cd target
    - mkdir java
    - mv sausage-store-${VERSION}.jar java
  rules:
    - changes:
        - backend/**/*
  artifacts:
    paths:
      - backend/target/java/sausage-store-${VERSION}.jar
      - ${CI_PROJECT_DIR}/backend/version.txt
    reports:
      dotenv: backend.env
  cache:
    key: backend_cache
    paths:
      - ${CI_PROJECT_DIR}/backend/.m2/repository # для хранения зависимости бекенда

upload-backend-release-job:
  stage: release
  needs:
    - build-backend-code-job
  script:
    - cd backend
    - mvn -Dmaven.repo.local=${CI_PROJECT_DIR}/backend/.m2/repository -s ${CI_PROJECT_DIR}/backend/settings.xml -Dversion.application=${VERSION} -DskipTests deploy
  cache:
    key: backend_cache
    paths:
      - ${CI_PROJECT_DIR}/backend/.m2/repository # для хранения зависимости бекенда
  rules:
    - changes:
        - backend/**/*


telegram-notification-backend:
  stage: notify
  only:
    changes:
        - "backend/*"
  variables:
    ARTIFACT_URL:
      ${NEXUS_REPO_URL_BACKEND}/com/yandex/practicum/devops/sausage-store/${VERSION}/sausage-store-${VERSION}.jar
  script:
    - curl -X POST -H "Content-type:application/json" --data '{"chat_id":"-1001634310929", "text":"Вышла новая версия backend сосисочной — '${VERSION}'. Скачать артефакт можно по ссылке — '${ARTIFACT_URL}'"}' "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage"
  needs:
    - backend-job
  # rules:
    # - if: $CI_COMMIT_MESSAGE =~ "/send notification/"
